---
galaxy_info:
  author: "Mradul"
  description: "Ansible role to create a VPC in AWS"
  company: "YourCompany"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Amazon
      versions:
        - all
dependencies: []
